export const QUERY_KEYS = Object.freeze({
  LIST_TOURS: 'LIST_TOURS',
  TOUR_DETAILS: 'TOUR_DETAILS',
  LIST_CITY: 'LIST_CITY',
  LATEST_NEWS: 'LATEST_NEWS',
  NEWS_DETAILS: 'NEWS_DETAILS',
  CURRENT: 'CURRENT',
  LIST_POST: 'LIST_POST',
  GET_POST_BY_ID: 'GET_POST_BY_ID',
  PROFILE: 'PROFILE',
  LIST_PROVINCE: 'LIST_PROVINCE',
  LIST_DISTRICT: 'LIST_DISTRICT',
  LIST_WARD: 'LIST_WARD',
});
